name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Fix go.mod Version
        run: |
          sed -i 's/1\.22\.2/1\.19/' go.mod

      - name: Get current version with Run Number
        id: get_version
        run: |
          run_number=${{ github.run_number }}
          next_version="v0.1.${run_number}"
          echo "next_version=$next_version" >> $GITHUB_ENV
          echo "Version to be created: $next_version"

      - name: Debug Token Permissions
        run: |
          echo "Checking token permissions"
          gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.next_version }}
          release_name: ${{ env.next_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.currentVersion=v${{ env.next_version }}" -o quacker-linux-amd64
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.currentVersion=v${{ env.next_version }}" -o quacker-linux-arm64

      - name: Upload Release Assets
        run: |
          gh release upload ${{ env.next_version }} ./quacker-linux-amd64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux ARM64 Binary
        run: |
          gh release upload ${{ env.next_version }} ./quacker-linux-arm64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
